[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "retina-esrd-survival"
version = "0.1.0"
description = "RETFound + DeepSurv survival pipeline for ESRD from retinal images"
authors = [{name="Effendy Bin Hashim"}]
requires-python = ">=3.10"
